apiVersion: v1
kind: Namespace
metadata:
  name: ns-qualification-task
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s-qualification-task
  namespace: ns-qualification-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-k8s-qualification-task
  template:
    metadata:
      labels:
        app: app-k8s-qualification-task
    spec:
      containers:
      - name: geo-app
        image: cr.yandex/crp1h3ir3dj4rbtunnhs/app-qualification-geo:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: svc-qualification-task 
  namespace: ns-qualification-task 
spec:
  selector:
    app: app-k8s-qualification-task
  ports:
  - name: web-http
    port: 8081
    targetPort: 80